@startuml


[*] --> NEW
NEW --> INFO_LOADED: loadInfo()
INFO_LOADED --> IN_PROGRESS: start()
IN_PROGRESS --> PAUSED: pause()
PAUSED --> IN_PROGRESS: start()
IN_PROGRESS --> COMPLETE: finished
IN_PROGRESS --> FAILED: failed
FAILED --> IN_PROGRESS: start()



@enduml
