    @startuml
    
    participant "app: App" as app
    participant "item: DownloadItem" as item
    participant "selector: TrackSelector" as selector
    
    group for type in VIDEO, AUDIO, TEXT
        app->selector: tracks = getAvailableTracks(type)
        note over app: filter tracks
        app->selector: setSelectedTracks(type, filteredTracks)
    end group
    app->selector: apply()
    
    @enduml
